import type { Player } from "./types";

// Helper builder to keep the seed compact
const p = (
  id:string, num:string, name:string, age:number, birth_year:number,
  nationality:string, flag:string, club:string, league:string, region:string,
  lat:number, lng:number,
  position_main:string, position_code:Player["position_code"],
  position_secondary:string[],
  foot:string, height:number, weight:number,
  tactical_roles:Player["tactical_roles"],
  ratings:Player["ratings"], skills:Player["skills"], stars:Player["stars"],
  market:Player["market"], tags:string[], verdict_type:Player["verdict_type"],
  observation_type:string, observation_count:number, date:string,
  strengths:string[], weaknesses:string[], summary:string, verdict:string,
): Player => ({
  id, num, name, photo:"", age, birth_year, nationality, flag, club, league, region,
  lat, lng, position_main, position_code, position_secondary, foot, height, weight,
  tactical_roles, ratings, skills, stars, market, tags, verdict_type, verdict,
  observation_type, observation_count, date, strengths, weaknesses, summary,
  video_url:"", raw_report:"",
});

export const SEED_PLAYERS: Player[] = [
  p("ndianga-sall","001","Ndianga Sall",22,2003,"Senegal","🇸🇳","Unione Sportiva Fasano","Serie D Girone H","Puglia",40.83,17.36,
    "Mediano","CM",["Mezzala"],"Destro",184,80,
    [{formation:"4-3-3",role:"Mezzala di Rottura",role_code:"CM_BOX",fit_score:90},
     {formation:"4-2-3-1",role:"Mediano di Copertura",role_code:"CDM_SCREEN",fit_score:72}],
    {technical:7.2,tactical:8.1,physical:7.8,mental:7.5,overall:7.6},
    {ball_control:74,passing:79,dribbling:68,finishing:52,defensive_work:77,tactical_iq:82,decision_making:76,aerial:70,pace:76,stamina:84},
    {technique:4,athleticism:4,mentality:4,potential:4,market_value:3},
    {value_min:60000,value_max:110000,potential:"Medio-Alto",risk:"Basso",timeline:"12-18 mesi",ready_level:"Serie C"},
    ["HIGH POTENTIAL","READY"],"buy","Video + Dal vivo",5,"2025-03-12",
    ["Copertura degli spazi","Pressing alto efficace","Fisico dominante"],
    ["Lettura tattica in ritardo","Scarsa precisione nei passaggi lunghi"],
    "Centrocampista senegalese con grande impatto fisico e ottima copertura degli spazi. Superiore alla categoria per intensità e capacità di recupero palla.",
    "Profilo immediatamente spendibile in Serie C. Fisicità e pressing lo rendono adatto a squadre di transizione rapida."),

  p("almamy-soumah","002","Almamy Soumah",20,2005,"Guinea","🇬🇳","ASD Bitonto","Serie D Girone H","Puglia",41.11,16.69,
    "Prima Punta","ST",["Ala Sinistra"],"Destro",180,75,
    [{formation:"4-3-3",role:"Prima Punta di Pressione",role_code:"ST_PRESSING",fit_score:88},
     {formation:"4-4-2",role:"Attaccante Centrale",role_code:"ST_TARGET",fit_score:71}],
    {technical:7.8,tactical:6.9,physical:8.2,mental:7.0,overall:7.6},
    {ball_control:78,passing:58,dribbling:80,finishing:72,defensive_work:42,tactical_iq:69,decision_making:70,aerial:65,pace:88,stamina:79},
    {technique:4,athleticism:5,mentality:3,potential:5,market_value:3},
    {value_min:90000,value_max:180000,potential:"Alto",risk:"Medio",timeline:"6-12 mesi",ready_level:"Serie C"},
    ["HIGH POTENTIAL","TOP PROSPECT"],"buy","Dal vivo",6,"2025-04-01",
    ["Accelerazione devastante","Pressing alto","Dribbling in velocità"],
    ["Finalizzazione inconsistente","Partecipazione alla manovra"],
    "Attaccante guineano esplosivo, potenziale da categoria superiore. La velocità è un'arma assoluta, ma la finalizzazione deve crescere.",
    "Da acquisire ora. Il profilo atletico è raro a questi livelli. Con lavoro sulla tecnica può arrivare in Serie B."),

  p("alessandro-galeota","003","Alessandro Galeota",24,2001,"Italia","🇮🇹","ASD Martina Franca","Eccellenza Puglia","Puglia",40.70,17.33,
    "Trequartista","CAM",["Mezzala"],"Destro",178,72,
    [{formation:"4-2-3-1",role:"Trequartista",role_code:"CAM_TREQUARTISTA",fit_score:91},
     {formation:"4-3-3",role:"Mezzala Offensiva",role_code:"CM_MEZZALA_OFF",fit_score:78}],
    {technical:8.3,tactical:7.9,physical:6.5,mental:8.2,overall:7.9},
    {ball_control:85,passing:84,dribbling:79,finishing:68,defensive_work:45,tactical_iq:86,decision_making:82,aerial:52,pace:66,stamina:68},
    {technique:5,athleticism:3,mentality:4,potential:4,market_value:3},
    {value_min:70000,value_max:130000,potential:"Medio-Alto",risk:"Basso",timeline:"6-12 mesi",ready_level:"Serie C"},
    ["READY","HIGH POTENTIAL"],"buy","Video + Dal vivo",4,"2025-02-20",
    ["Visione di gioco verticale","Tocco di prima","Lettura tattica superiore"],
    ["Fisico limitato nei contrasti","Scarsa corsa difensiva"],
    "Fantasista tecnico con intelligenza tattica rara all'Eccellenza. Gioca tra le linee con naturalezza, gestisce i ritmi e crea superiorità numerica.",
    "Pronto per Serie D adesso, Serie C con 6 mesi di adattamento. Basso rischio, alta qualità tecnica."),

  p("ousmane-sassey","004","Ousmane Sassey",23,2002,"Costa d'Avorio","🇨🇮","FC Vigor Senigallia","Serie D Girone F","Puglia",40.95,17.06,
    "Difensore Centrale","CB",["Mediano"],"Destro",190,85,
    [{formation:"4-4-2",role:"Difensore Centrale Stopper",role_code:"CB_STOPPER",fit_score:85},
     {formation:"3-5-2",role:"Braccetto Difensivo",role_code:"CB_BALL_PLAYING",fit_score:68}],
    {technical:6.8,tactical:7.6,physical:8.5,mental:7.4,overall:7.5},
    {ball_control:65,passing:68,dribbling:48,finishing:35,defensive_work:84,tactical_iq:76,decision_making:72,aerial:85,pace:74,stamina:82},
    {technique:3,athleticism:5,mentality:4,potential:3,market_value:3},
    {value_min:50000,value_max:90000,potential:"Medio",risk:"Basso",timeline:"18-24 mesi",ready_level:"Serie D"},
    ["READY"],"monitor","Video",3,"2025-01-15",
    ["Dominio aereo","Aggressività nei duelli","Copertura spazio"],
    ["Costruzione dal basso lacunosa","Lentezza in uscita palla"],
    "Difensore centrale ivoriano con presenza fisica importante. Affidabile nei duelli ma limitato nel gioco con la palla. Profilo da monitorare.",
    "Tenerlo in lista per ruolo di copertura in squadre che cercano fisicità pura in difesa."),

  p("marco-puccio","005","Marco Puccio",26,1999,"Italia","🇮🇹","ASD Nardò Calcio","Serie D Girone H","Puglia",40.18,18.03,
    "Portiere","GK",[],"Destro",188,82,
    [{formation:"4-3-3",role:"Portiere Sweeper",role_code:"GK_SWEEPER",fit_score:82},
     {formation:"4-4-2",role:"Portiere Shot Stopper",role_code:"GK_SHOT_STOPPER",fit_score:76}],
    {technical:7.1,tactical:7.8,physical:7.5,mental:8.0,overall:7.6},
    {ball_control:72,passing:74,dribbling:30,finishing:20,defensive_work:80,tactical_iq:78,decision_making:80,aerial:79,pace:62,stamina:75},
    {technique:4,athleticism:4,mentality:4,potential:3,market_value:3},
    {value_min:40000,value_max:80000,potential:"Medio",risk:"Basso",timeline:"12-18 mesi",ready_level:"Serie C"},
    ["READY","LOW COST"],"buy","Dal vivo",5,"2025-03-28",
    ["Uscite alte sicure","Distribuzione con i piedi precisa","Comunicazione con la difesa"],
    ["Riflessi nei tiri ravvicinati","Gestione del cross"],
    "Portiere esperto e affidabile, fuori categoria per maturità. Ottima costruzione dal basso, profilo ideale per squadre che giocano a calcio.",
    "Portiere pronto per Serie C a basso costo. Affidabile e tecnico."),

  p("mattia-romani","006","Mattia Romani",19,2006,"Italia","🇮🇹","ASD Ginosa","Eccellenza Puglia","Puglia",40.58,16.77,
    "Terzino Sinistro","LB",["Ala Sinistra"],"Sinistro",179,72,
    [{formation:"3-5-2",role:"Wing Back Sinistro di Spinta",role_code:"LB_WING_BACK",fit_score:90},
     {formation:"4-3-3",role:"Terzino Sinistro Offensivo",role_code:"LB_INVERTED",fit_score:75}],
    {technical:7.0,tactical:7.2,physical:7.6,mental:6.8,overall:7.1},
    {ball_control:71,passing:73,dribbling:74,finishing:48,defensive_work:65,tactical_iq:70,decision_making:67,aerial:60,pace:80,stamina:78},
    {technique:3,athleticism:4,mentality:3,potential:5,market_value:3},
    {value_min:30000,value_max:70000,potential:"Alto",risk:"Medio",timeline:"18-24 mesi",ready_level:"Serie D"},
    ["HIGH POTENTIAL","LOW COST"],"monitor","Video + Dal vivo",3,"2025-04-05",
    ["Spinta continua sulla fascia","Cross di qualità","Velocità di esecuzione"],
    ["Fase difensiva da migliorare","Lettura tattica ancora acerba"],
    "Terzino sinistro di spinta classe 2006, talento grezzo con gamba importante. Fascia sinistra come principale fonte di gioco.",
    "Da seguire nei prossimi 12 mesi. Potenziale alto se cresce tatticamente."),

  p("karim-benali","007","Karim Benali",25,2000,"Algeria","🇩🇿","FC Catanzaro Primavera","Promozione Calabria","Calabria",38.90,16.59,
    "Mediano","CDM",["Regista"],"Destro",182,76,
    [{formation:"4-2-3-1",role:"Mediano Schermo",role_code:"CDM_SCREEN",fit_score:88},
     {formation:"4-3-3",role:"Regista Basso",role_code:"CM_REGISTA",fit_score:79}],
    {technical:7.4,tactical:8.4,physical:7.2,mental:8.1,overall:7.8},
    {ball_control:75,passing:83,dribbling:62,finishing:44,defensive_work:82,tactical_iq:85,decision_making:80,aerial:68,pace:68,stamina:80},
    {technique:4,athleticism:3,mentality:4,potential:4,market_value:3},
    {value_min:65000,value_max:120000,potential:"Medio-Alto",risk:"Basso",timeline:"12 mesi",ready_level:"Serie D"},
    ["HIGH POTENTIAL","READY"],"buy","Video + Dal vivo",4,"2025-02-10",
    ["Intercettazioni frequenti","Distribuzione verticale","Posizionamento difensivo"],
    ["Scarsa presenza offensiva","Lento nell'uno contro uno"],
    "Mediano algerino intelligente e posizionalmente preciso. Schermo ideale davanti alla difesa, lettura del gioco superiore alla categoria.",
    "Da prendere subito. Profilo da squadra di Serie D organizzata."),

  p("luca-ferrante","008","Luca Ferrante",21,2004,"Italia","🇮🇹","US Salernitana U19","Under 19 Regionale Campania","Campania",40.68,14.76,
    "Ala Destra","RW",["Trequartista"],"Sinistro",176,68,
    [{formation:"4-3-3",role:"Ala Destra Accentrante",role_code:"RW_INVERTED",fit_score:92},
     {formation:"4-2-3-1",role:"Esterno Trequartista",role_code:"CAM_SHADOW",fit_score:70}],
    {technical:7.9,tactical:7.0,physical:7.3,mental:7.4,overall:7.5},
    {ball_control:82,passing:74,dribbling:85,finishing:70,defensive_work:50,tactical_iq:71,decision_making:73,aerial:54,pace:82,stamina:72},
    {technique:5,athleticism:4,mentality:3,potential:5,market_value:2},
    {value_min:20000,value_max:50000,potential:"Alto",risk:"Medio",timeline:"24 mesi",ready_level:"Eccellenza"},
    ["HIGH POTENTIAL","TOP PROSPECT","LOW COST"],"monitor","Video",2,"2025-04-10",
    ["Dribbling in velocità","Taglio dentro al campo","Conclusione col sinistro"],
    ["Fase difensiva assente","Inconsistenza nelle partite importanti"],
    "Esterno destro classe 2004, dribblomane puro. Capace di saltare l'uomo con facilità disarmante per categoria Under 19.",
    "Monitorare con attenzione. Un anno di Eccellenza o Serie D cambierebbe la valutazione."),

  p("antonio-esposito","009","Antonio Esposito",28,1997,"Italia","🇮🇹","ASD Ercolanese","Eccellenza Campania","Campania",40.80,14.35,
    "Seconda Punta","CF",["Trequartista"],"Destro",181,77,
    [{formation:"4-4-2",role:"Seconda Punta",role_code:"CF_SECONDA_PUNTA",fit_score:86},
     {formation:"4-3-3",role:"Falso Nueve",role_code:"CF_FALSE_9",fit_score:80}],
    {technical:7.6,tactical:7.8,physical:6.8,mental:8.3,overall:7.6},
    {ball_control:78,passing:77,dribbling:70,finishing:74,defensive_work:56,tactical_iq:80,decision_making:82,aerial:61,pace:65,stamina:70},
    {technique:4,athleticism:3,mentality:4,potential:2,market_value:3},
    {value_min:35000,value_max:65000,potential:"Basso",risk:"Basso",timeline:"Immediato",ready_level:"Serie D"},
    ["READY","LOW COST"],"buy","Video + Dal vivo",6,"2025-01-30",
    ["Mobilità tattica","Associazione con i compagni","Intelligenza negli spazi"],
    ["Età avanzata limita la rivalutazione","Esplosività in calo"],
    "Attaccante napoletano esperto, profilo da falso nueve maturo. Movimento intelligente, ottimo raccordo tra i reparti. Nessun margine di crescita ma altamente affidabile.",
    "Profilo da prendere subito se si cerca qualità ed esperienza a basso costo. Zero rischio."),

  p("diallo-camara","010","Diallo Camara",18,2007,"Guinea-Bissau","🇬🇼","ASD Polisportiva Agropoli","Promozione Campania","Campania",40.35,14.99,
    "Ala Sinistra","LW",[],"Destro",177,68,
    [{formation:"4-3-3",role:"Ala Sinistra Pura",role_code:"LW_WINGER",fit_score:85},
     {formation:"3-4-3",role:"Ala Sinistra Accentrante",role_code:"LW_INVERTED",fit_score:72}],
    {technical:7.3,tactical:6.5,physical:7.8,mental:6.7,overall:7.0},
    {ball_control:76,passing:62,dribbling:82,finishing:60,defensive_work:40,tactical_iq:65,decision_making:62,aerial:55,pace:90,stamina:74},
    {technique:4,athleticism:5,mentality:3,potential:5,market_value:2},
    {value_min:15000,value_max:40000,potential:"Alto",risk:"Alto",timeline:"24-36 mesi",ready_level:"Eccellenza"},
    ["HIGH POTENTIAL","RISKY","LOW COST"],"monitor","Dal vivo",2,"2025-04-08",
    ["Velocità pura eccezionale","Dribbling istintivo","Potenziale atletico"],
    ["Decisioni affrettate","Tattica lacunosa","Difesa inesistente"],
    "Ala classe 2007, grezzo ma con doti atletiche rare per l'età. La velocità è da professionista. Tutto il resto è da costruire.",
    "Alto rischio, altissima upside. Solo per chi può investire 2-3 anni nel suo sviluppo."),

  p("raffaele-montemurro","011","Raffaele Montemurro",22,2003,"Italia","🇮🇹","FC Melfi","Serie D Girone I","Basilicata",40.99,15.65,
    "Terzino Destro","RB",[],"Destro",181,75,
    [{formation:"3-5-2",role:"Wing Back Destro di Spinta",role_code:"RB_WING_BACK",fit_score:88},
     {formation:"4-3-3",role:"Terzino Destro Classico",role_code:"RB_CLASSIC",fit_score:74}],
    {technical:6.9,tactical:7.5,physical:7.7,mental:7.3,overall:7.3},
    {ball_control:70,passing:74,dribbling:67,finishing:45,defensive_work:75,tactical_iq:74,decision_making:71,aerial:68,pace:79,stamina:83},
    {technique:3,athleticism:4,mentality:4,potential:3,market_value:3},
    {value_min:45000,value_max:85000,potential:"Medio",risk:"Basso",timeline:"12-18 mesi",ready_level:"Serie D"},
    ["READY"],"monitor","Video + Dal vivo",3,"2025-03-05",
    ["Resistenza fisica eccellente","Spinta continua sulla fascia","Disciplina tattica"],
    ["Qualità del cross da migliorare","Scarso nelle uscite palla"],
    "Terzino destro lucano affidabile e generoso. Ottimo motorino sulla fascia, ma ancora grezzo tecnicamente.",
    "Profilo solido per Serie D. Da seguire una stagione prima di valutare un eventuale salto."),

  p("sebastiano-fallara","012","Sebastiano Fallara",17,2008,"Italia","🇮🇹","Reggina Academy","Under 19 Regionale Calabria","Calabria",38.11,15.66,
    "Difensore Centrale","CB",[],"Destro",185,73,
    [{formation:"4-3-3",role:"Difensore Centrale con Palla",role_code:"CB_BALL_PLAYING",fit_score:79},
     {formation:"3-5-2",role:"Braccetto Centrale",role_code:"CB_LIBERO",fit_score:68}],
    {technical:7.0,tactical:6.8,physical:7.4,mental:7.1,overall:7.0},
    {ball_control:72,passing:71,dribbling:55,finishing:38,defensive_work:70,tactical_iq:68,decision_making:67,aerial:74,pace:70,stamina:74},
    {technique:3,athleticism:4,mentality:3,potential:5,market_value:2},
    {value_min:10000,value_max:30000,potential:"Alto",risk:"Alto",timeline:"36+ mesi",ready_level:"Eccellenza"},
    ["HIGH POTENTIAL","LOW COST","TOP PROSPECT"],"pass","Video",1,"2025-04-12",
    ["Impostazione dal basso pulita","Buon senso del posizionamento","Testa alta"],
    ["Troppo giovane per valutazione definitiva","Fisico ancora acerbo","Un'unica osservazione insufficiente"],
    "Difensore classe 2008 dalla Reggina Academy. Una sola osservazione non basta. Promettente nell'impostazione ma tutto da valutare.",
    "Scartare per ora — non abbastanza dati. Reinserire in lista il prossimo anno con più osservazioni."),
];
